Removed unnecessarily exposed ports
samagra-comms/docker-deploy pull request #49
Opened 2023-04-25 08:26 UTC by RyanWalker277

Fixes #48

2023-04-25 08:29 UTC, RyanWalker277 commented
https://github.com/samagra-comms/docker-deploy/blob/c67da57c8830547baa362b11c2660056a1fed4f1/docker-compose.yml#L224-L229

I am a bit unsure about these ports, they dont seem to be used by any other service. Let me know if I can unexpose these as well.

2023-04-25 13:28 UTC, tushar5526 commented on docker-compose.yml
> -    ports:
This has to be exposed

2023-04-25 13:30 UTC, tushar5526 commented
Items to be exposed.

- everything having a UI viz hasura, aggregate-server etc.
- items not having a UI or used internally through docker compose network, Caches, DB, other services where internal ports are being used (eg: Kafka)

2023-04-25 13:46 UTC, tushar5526 commented on docker-compose.yml
> -    ports:
similarly a lot of other things needs to be exposed.

2023-04-27 03:56 UTC, tushar5526 requested changes
You have not fixed every mount. Please go through all comments and resolve one by one.

2023-04-27 04:08 UTC, tushar5526 commented on docker-compose.yml
> -    ports:
Vault is needed publicly

2023-04-27 04:10 UTC, merged